version: '3.9'
services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpasswordalo"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  orchestrator:
    build:
      context: ./
      dockerfile: Docker/orchestrator/Dockerfile
    environment:
      POSTGRES_STRING: "postgresql://postgres:mysecretpasswordalo@postgres:5432/postgres?sslmode=disable"
      HMAC: "GFBKJWABGJKWHABGJWAHBGWAKLWKJNGLKJNKABWGH"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  user_server:
    build:
      context: .
      dockerfile: Docker/user_server/Dockerfile
    ports:
      - "80:80"

  agents:
    build:
      context: .
      dockerfile: Docker/agent/Dockerfile
    environment:
      AGENT_COUNT: "5"
      POSTGRES_STRING: "postgresql://postgres:mysecretpasswordalo@postgres:5432/postgres?sslmode=disable"
    ports:
      - "9090:9090"
    depends_on:
      - postgres

#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4:7
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "10110:80"

volumes:
  postgres:
#  pgadmin: