FROM golang:latest AS builder
EXPOSE 80

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download
COPY ./templates ./templates
COPY ./internal ./internal
COPY ./cmd/user_server ./cmd/user_server

RUN go build -o user_server ./cmd/user_server

CMD ["/app/user_server"]
